apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 010-kubeflow-roles
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
{{ .Values.kubeflowRolesSpec | toYaml | indent 2}}