apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-cert
  namespace: istio-system
spec:
  commonName: <patch me>
  dnsNames:
    - <patch me>
  issuerRef:
    kind: Issuer
    name: treebeard-issuer
  secretName: gateway-cert
---