apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps2
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: argo-cd
    server: 'https://kubernetes.default.svc'
  source:
    path: apps2
    repoURL: >-
      https://github.com/treebeardtech/gitops-bridge-argocd-control-plane-template
    targetRevision: dev
  sources: []
  project: default
  # syncPolicy:
  #   automated:
  #     prune: false