apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-cert
spec:
  commonName: '{{ .Values.hostname }}'
  dnsNames:
    - '{{ .Values.hostname }}'
  issuerRef:
    kind: Issuer
    name: treebeard-issuer
  secretName: gateway-cert