apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 100-jupyter-web-app
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
{{ .Values.jupyterWebAppSpec | toYaml | indent 2}}